package com.br.equaly.auth.domain.enums;

public enum Role {
    EQUALY_MASTER_ADMIN,
    MASTER_ADMIN,
    COMMON_ADMIN,
    COMMON_EVENT_OPENER,
    MASTER_EVENT_OPENER,
    COMMON_QUALITY_INSPECTOR,
    MASTER_QUALITY_INSPECTOR,
    COMMON_RNC_REPORTER
}