name: Trigger auto deployment for equalyiam

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - '**'
    - '.github/workflows/equalyiam-AutoDeployTrigger-0b31b26b-95ce-4992-b93d-12c3e2d4a679.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.EQUALYIAM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EQUALYIAM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EQUALYIAM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: equalycentral.azurecr.io
          registryUsername: ${{ secrets.EQUALYIAM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EQUALYIAM_REGISTRY_PASSWORD }}
          containerAppName: equalyiam
          resourceGroup: eQualyBackendResourceGroup
          imageToBuild: equalycentral.azurecr.io/equalyiam:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


